CREATE DATABASE JOINSEXAMPLES;

USE JOINSEXAMPLES


CREATE TABLE STUDENT
(
	ID INT NOT NULL,
	SNAME VARCHAR(30),
	CID INT
);
CREATE TABLE COURSE
(
	CID INT NOT NULL,
	CNAME VARCHAR(30),
	FEES FLOAT
);

--INSERT STUDENT
INSERT INTO STUDENT VALUES(1,'AAAAAAA',11)
INSERT INTO STUDENT VALUES(2,'BBBBBBB',22)
INSERT INTO STUDENT VALUES(3,'CCCCCC',11)
INSERT INTO STUDENT VALUES(4,'DDDDDDD',33)
INSERT INTO STUDENT VALUES(5,'EEEEEEE',11)
INSERT INTO STUDENT VALUES(6,'GGGGGGG',99)
INSERT INTO STUDENT VALUES(7,'FFFFFFF',98)

SELECT * FROM STUDENT;

--INSERT COURSE
INSERT INTO COURSE VALUES(11,'PYTHON',8000);
INSERT INTO COURSE VALUES(22,'C',4000);
INSERT INTO COURSE VALUES(33,'HTML',6000);
INSERT INTO COURSE VALUES(44,'JAVA',8000);
INSERT INTO COURSE VALUES(55,'CSHARP',9000);
SELECT * FROM COURSE;


SELECT * FROM STUDENT S
LEFT JOIN COURSE C
ON S.CID=C.CID

SELECT * FROM STUDENT S
RIGHT JOIN COURSE C
ON S.CID=C.CID


SELECT * FROM STUDENT S
INNER JOIN COURSE C
ON S.CID=C.CID






