--INSERTION AT CATEGORIES SHOULD BE DONE FIRST AS THE PRODUCTS DEPENDS ON CID

INSERT INTO CATEGORIES VALUES(100,'SOAPS','BATHING SOAPS');
INSERT INTO CATEGORIES VALUES(101,'PASTE','DENTAL PRODUCTS');
INSERT INTO CATEGORIES VALUES(102,'SHAMPOOS','HAIR PRODUCTS');
INSERT INTO CATEGORIES VALUES(103,'CREAMS','FACIAL PRODUCTS');
INSERT INTO CATEGORIES VALUES(104,'SANITIZATION','CLEANING PRODUCTS');


SELECT * FROM CATEGORIES;

insert into PRODUCTS VALUES(1,'LUX',45,100);
insert into PRODUCTS VALUES(2,'LIRIL',55,100);
insert into PRODUCTS VALUES(3,'LIZOL',75,104);
insert into PRODUCTS VALUES(4,'HARPIC',85,104);
insert into PRODUCTS VALUES(5,'COLGATE',45,101);
insert into PRODUCTS VALUES(6,'SUNSILK',65,102);
insert into PRODUCTS VALUES(7,'PONDS',110,103);
insert into PRODUCTS VALUES(8,'GARNIER',95,103);
insert into PRODUCTS VALUES(9,'HIMALAYAS',85,102);
insert into PRODUCTS VALUES(10,'PEPSODENT',45,101);

SELECT * FROM PRODUCTS;

--ALTERING (DROPPING THE CONSTRAINT CREATED FIRST)
ALTER TABLE CUSTOMERS
 DROP CONSTRAINT FK__CUSTOMERS__ORDER__2E1BDC42;

--ALTERING THE TABLE CUSTOMERS ( WE ARE DELETING COLUMN ORDERID  )
ALTER TABLE  CUSTOMERS
DROP COLUMN ORDERID

INSERT INTO CUSTOMERS VALUES(1000,'SANJAY','SANJAY@GMAIL.COM')
INSERT INTO CUSTOMERS VALUES(1001,'AJAY','AJAY@GMAIL.COM')
INSERT INTO CUSTOMERS VALUES(1002,'SANDHYA','SANDHYA@GMAIL.COM')
INSERT INTO CUSTOMERS VALUES(1003,'CHANDANA','CHANDANA@GMAIL.COM')
INSERT INTO CUSTOMERS VALUES(1004,'AARTI','AARTI@GMAIL.COM')
INSERT INTO CUSTOMERS VALUES(1005,'DEEPAK','DEEPAK@GMAIL.COM')
INSERT INTO CUSTOMERS VALUES(1006,'CHANDANA','CHANDANA1@GMAIL.COM')

SELECT * FROM CUSTOMERS;
SELECT * FROM PRODUCTS;

INSERT INTO ORDERS VALUES(500,1001,3,4);
INSERT INTO ORDERS VALUES(501,1002,6,3);
INSERT INTO ORDERS VALUES(502,1001,3,4);
INSERT INTO ORDERS VALUES(503,1003,8,2);
INSERT INTO ORDERS VALUES(504,1005,9,4);
INSERT INTO ORDERS VALUES(505,1004,8,3);
INSERT INTO ORDERS VALUES(506,1003,4,4);
INSERT INTO ORDERS VALUES(507,1003,7,2);
INSERT INTO ORDERS VALUES(508,1006,7,2);

SELECT * FROM  ORDERS;

--PULL OUT THE CUSTIDS WRT CHANDANA
SELECT CUSTID
FROM CUSTOMERS
WHERE CUSTNAME = 'CHANDANA'


SELECT ORDERID
FROM ORDERS
WHERE CUSTID IN (SELECT CUSTID
FROM CUSTOMERS
WHERE CUSTNAME = 'CHANDANA')


SELECT PNAME ,ORDERS.ORDERID
FROM PRODUCTS,ORDERS
WHERE PRODUCTS.PID IN(
	SELECT PID
	FROM ORDERS
	WHERE CUSTID IN (SELECT CUSTID
	FROM CUSTOMERS
	WHERE CUSTNAME = 'CHANDANA')) AND PRODUCTS.PID=ORDERS.PID;



SELECT PNAME ,ORDERS.ORDERID,CUSTOMERS.CUSTID
FROM PRODUCTS,ORDERS,CUSTOMERS
WHERE PRODUCTS.PID IN(
	SELECT PID
	FROM ORDERS
	WHERE CUSTID IN (SELECT CUSTID
	FROM CUSTOMERS
	WHERE CUSTNAME = 'CHANDANA')) AND PRODUCTS.PID=ORDERS.PID AND ORDERS.CUSTID = CUSTOMERS.CUSTID;






SELECT * FROM PRODUCTS;
SELECT * FROM CATEGORIES;


SELECT P.*,C.CNAME,C.CDESCRIPTION
FROM PRODUCTS AS P,CATEGORIES AS C
WHERE P.CID=C.CID



--CUSTOMERSID -> NO OF ORDERS PLACED
SELECT CUSTID,COUNT(CUSTID)
FROM ORDERS
GROUP BY CUSTID
HAVING COUNT(CUSTID) > 0;

--CUSTOMER NAMES, ORDERID  WITH MORE THAN  1 ORDER


SELECT CUSTOMERS.CUSTNAME,CUSTOMERS.CUSTID,COUNT(ORDERS.CUSTID)
FROM CUSTOMERS,ORDERS
WHERE CUSTOMERS.CUSTID=ORDERS.CUSTID AND  CUSTOMERS.CUSTID IN (
			SELECT CUSTID
			FROM ORDERS
			GROUP BY CUSTID
			HAVING COUNT(CUSTID) > 1)  
		GROUP BY CUSTOMERS.CUSTNAME,CUSTOMERS.CUSTID;




SELECT * FROM ORDERS
SELECT * FROM PRODUCTS


SELECT O.ORDERID,O.CUSTID,SUM(P.PRICE*O.QUANTITY) AS NEWPRICE
FROM PRODUCTS P,ORDERS O
WHERE O.PID = P.PID
GROUP BY O.CUSTID,O.ORDERID







SELECT O.CUSTID,COUNT(O.CUSTID) AS NOOFORDERS,SUM(P.PRICE*O.QUANTITY) AS NEWPRICE
FROM ORDERS O,PRODUCTS P
WHERE O.PID = P.PID
GROUP BY O.CUSTID
HAVING COUNT(O.CUSTID)>=1





SELECT * FROM ORDERS;

SELECT * FROM CUSTOMERS;
INSERT INTO CUSTOMERS VALUES(1007,'SHANKAR','SHANKAR@GMAIL.COM')

SELECT *
FROM ORDERS
LEFT JOIN CUSTOMERS
ON ORDERS.CUSTID = CUSTOMERS.CUSTID



SELECT *
FROM ORDERS
RIGHT JOIN CUSTOMERS
ON ORDERS.CUSTID = CUSTOMERS.CUSTID



INSERT INTO CATEGORIES VALUES(105,'PERFUMES','SCENTS & FRAGRANCE')
SELECT * FROM CATEGORIES;

SELECT *
FROM CATEGORIES C
LEFT JOIN PRODUCTS P
ON P.CID = C.CID

SELECT * FROM CATEGORIES























